apiVersion: v1
kind: Pod
metadata:
  name: kaniko-sandbox
  namespace: dsh-build
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: ghcr-push
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--context=tar:///context/context.tar.gz"
        - "--dockerfile=docker/dsh-sandbox-daemon.Dockerfile"
        - "--destination=ghcr.io/visecy/dsh-sandbox-daemon:0.1.0"
        - "--registry-mirror=docker.1panel.live"
        - "--cache=false"
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
        - name: build-context
          mountPath: /context
  volumes:
    - name: docker-config
      secret:
        secretName: ghcr-push
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: build-context
      secret:
        secretName: dsh-build-context
