apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dsh-control-plane.fullname" . }}-plugins
  labels:
    {{- include "dsh-control-plane.labels" . | nindent 4 }}
data:
  auth-oidc-plugin.js: |-
{{ .Files.Get "files/auth-oidc-plugin.js" | indent 4 }}
  fs-k8s.js: |-
{{ .Files.Get "files/fs-k8s.js" | indent 4 }}
  subprocess-k8s.js: |-
{{ .Files.Get "files/subprocess-k8s.js" | indent 4 }}
  workspace-k8s.js: |-
{{ .Files.Get "files/workspace-k8s.js" | indent 4 }}
  pkg-auth-oidc.json: |-
{{ .Files.Get "files/pkg-auth-oidc.json" | indent 4 }}
  pkg-fs-k8s.json: |-
{{ .Files.Get "files/pkg-fs-k8s.json" | indent 4 }}
  pkg-subprocess-k8s.json: |-
{{ .Files.Get "files/pkg-subprocess-k8s.json" | indent 4 }}
  pkg-workspace-k8s.json: |-
{{ .Files.Get "files/pkg-workspace-k8s.json" | indent 4 }}
  cordis.patch.yml: |-
{{ .Files.Get "files/cordis.patch.yml" | indent 4 }}
